footer_scripts:
  type: string
  default: ""
  description:
    en: "Custom footer scripts (analytics, counters, etc.). This code will be inserted before closing </body> tag on all pages."
    ru: "Пользовательские скрипты для футера (аналитика, счетчики и т.д.). Этот код будет вставлен перед закрывающим тегом </body> на всех страницах."

yandex_metrika_id:
  type: string
  default: ""
  description:
    en: "Yandex Metrika counter ID (only numbers)"
    ru: "ID счетчика Яндекс.Метрики (только цифры)"

google_analytics_id:
  type: string
  default: ""
  description:
    en: "Google Analytics 4 Measurement ID (format: G-XXXXXXXXXX)"
    ru: "ID Google Analytics 4 (формат: G-XXXXXXXXXX)"

enable_yandex_metrika:
  type: bool
  default: false
  description:
    en: "Enable Yandex Metrika counter"
    ru: "Включить счетчик Яндекс.Метрики"

enable_google_analytics:
  type: bool
  default: false
  description:
    en: "Enable Google Analytics 4"
    ru: "Включить Google Analytics 4"

enable_custom_footer_scripts:
  type: bool
  default: false
  description:
    en: "Enable custom footer scripts"
    ru: "Включить пользовательские скрипты футера"
