footer_scripts:
  type: list
  list_type: compact
  default: ""
  description:
    en: "Custom footer scripts (analytics, counters, etc.). This code will be inserted before closing </body> tag on all pages. Each line will be added as separate HTML."
    ru: "Пользовательские скрипты для футера (аналитика, счетчики и т.д.). Этот код будет вставлен перед закрывающим тегом </body> на всех страницах. Каждая строка будет добавлена как отдельный HTML."

custom_meta_tags:
  type: list
  list_type: compact
  default: ""
  description:
    en: "Custom meta tags for the head section. Enter HTML meta tags, one per line (e.g., <meta name='author' content='Your Name'>)"
    ru: "Пользовательские мета-теги для секции head. Введите HTML мета-теги, по одному на строку (например, <meta name='author' content='Ваше имя'>)"

custom_head_scripts:
  type: list
  list_type: compact
  default: ""
  description:
    en: "Custom scripts for the head section (tracking pixels, verification codes, etc.). Each line will be added as separate HTML."
    ru: "Пользовательские скрипты для секции head (пиксели отслеживания, коды верификации и т.д.). Каждая строка будет добавлена как отдельный HTML."

yandex_metrika_id:
  type: string
  default: ""
  description:
    en: "Yandex Metrika counter ID (only numbers)"
    ru: "ID счетчика Яндекс.Метрики (только цифры)"

google_analytics_id:
  type: string
  default: ""
  description:
    en: "Google Analytics 4 Measurement ID (format: G-XXXXXXXXXX)"
    ru: "ID Google Analytics 4 (формат: G-XXXXXXXXXX)"

enable_yandex_metrika:
  type: bool
  default: false
  description:
    en: "Enable Yandex Metrika counter"
    ru: "Включить счетчик Яндекс.Метрики"

enable_google_analytics:
  type: bool
  default: false
  description:
    en: "Enable Google Analytics 4"
    ru: "Включить Google Analytics 4"

enable_custom_footer_scripts:
  type: bool
  default: false
  description:
    en: "Enable custom footer scripts"
    ru: "Включить пользовательские скрипты футера"

enable_custom_meta_tags:
  type: bool
  default: false
  description:
    en: "Enable custom meta tags"
    ru: "Включить пользовательские мета-теги"

enable_custom_head_scripts:
  type: bool
  default: false
  description:
    en: "Enable custom head scripts"
    ru: "Включить пользовательские скрипты в head"
