yandex_metrika_id:
  type: string
  default: ""
  description:
    en: "Yandex Metrika counter ID (only numbers)"
    ru: "ID счетчика Яндекс.Метрики (только цифры)"

enable_yandex_metrika:
  type: bool
  default: false
  description:
    en: "Enable Yandex Metrika counter"
    ru: "Включить счетчик Яндекс.Метрики"

test_custom_code:
  type: string
  default: ""
  description:
    en: "Test custom code"
    ru: "Тестовый пользовательский код"
